## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
frame = pd.DataFrame(data)
print(frame)


     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))



0     apple
1    banana
2    carrot
3    banana
4    banana
5    carrot
6     apple
7    carrot
8     apple
9     apple
dtype: object


In [ ]:
# Type your solution here
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

df = pd.concat([fruit, weights], axis = 1)
print(df)


select_apple = df.loc[df[0] == 'apple']
#print(select_apple)
a = select_apple.mean()
print("The mean weight for apples is: ", a)

select_banana = df.loc[df[0] == 'banana']
#print(select_banana)
b = select_banana.mean()
print("The mean weight for bananas is:", b)

select_carrot = df.loc[df[0] == 'carrot']
#print(select_carrot)
c = select_carrot.mean()
print("The mean weight for carrots is:", c)


        0     1
0  carrot   1.0
1   apple   2.0
2  banana   3.0
3  banana   4.0
4  carrot   5.0
5   apple   6.0
6   apple   7.0
7   apple   8.0
8  carrot   9.0
9   apple  10.0
The mean weight for apples is:  1    6.6
dtype: float64
The mean weight for bananas is: 1    3.5
dtype: float64
The mean weight for carrots is: 1    5.0
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
print("Original array:")
print(course_name)
i = np.argsort(course_name)
print("Indices of the sorted elements of a given array:")
print(i)
print("Check if each element of the array starts with 'P':")
s = np.char.startswith(course_name, "P")
print(s)


Original array:
['Python' 'JS' 'examples' 'PHP' 'html']
Indices of the sorted elements of a given array:
[1 3 0 2 4]
Check if each element of the array starts with 'P':
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here
print("The original list is:") 
print(student_id)
# Function to reverse list
def reverseList(student_id, start, end):
    while start < end:
        student_id[start], student_id[end] = student_id[end], student_id[start]
        start += 1
        end -= 1
reverseList(student_id, 0, 6)
print("Reversed list is")
print(student_id)

import sys
# Function to print three largest 
def print3largest(arr, arr_size):   
    third = first = second = -sys.maxsize
    for i in range(0, 6):
        if (arr[i] > first):
         
            third = second
            second = first
            first = arr[i]

        # If i is in between first and second then update second 
        elif (arr[i] > second):
         
            third = second
            second = arr[i]
         
        elif (arr[i] > third):
            third = arr[i]
     
    print("Three largest elements are",
                  first, second, third)
n = len(student_id)
print3largest(student_id, n) 

The original list is:
[1023 5202 6230 1671 1682 5241 4532]
Reversed list is
[4532 5241 1682 1671 6230 5202 1023]
Three largest elements are 6230 5241 5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
import numpy as np
x = np.arange(1, 100)
# find all multiples of 3 or 5 below 100
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:100])
# print the sum 
print(n.sum())


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
arr[:, [1, 0]] = arr[:, [0, 1]] 
print("After swapping arrays the last column and first column:") 
print(arr)


After swapping arrays the last column and first column:
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)
a = pd.DataFrame(arr)
b, c = a.iloc[0], a.iloc[1]

print("After swapping row 0 with row 1")
temp = a.iloc[0].copy()
a.iloc[0] = c
a.iloc[1] = temp

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
